name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug]

body:

- type: input
  id: title
  attributes:
    label:  Название
    description: |
      Последовательный ответ на три вопроса:
      ЧТО не так работает?
      ГДЕ не работает, в каком месте продукта?
      КОГДА данная проблема проявляется?
    placeholder:  "Что? Где? Когда?"
  validations:
    required: true
    
- type: textarea
  id: bug_description
  attributes:
    label:  Описание
    description: "Описание возникшей ошибки и мнение как её можно исправить"
    value: " - "
    render: markdown
  validations:
    required: true
    
- type: input
  id: bug_expected
  attributes:
    label:  Ожидаемый результат
    description: "ожидаемое поведение тестируемого объекта"
     placeholder:  " "
  validations:
    required: true
    
- type: input
  id: bug_actual
  attributes:
    label: Актуальный результат
    description: "реальное поведение тестируемого объекта"
     placeholder:  " "
  validations:
    required: true
    
- type: input
  id: bug_url
  attributes:
    label: Локация дефекта
    description: "Локация дефекта — это не место с тестом, а место тестируемого класса, где, на ваш взгляд, происходит дефект; можно указать просто на первую строчку объявления метода или вставить ссылку. Чтобы красиво сослаться на нужное место в коде, откройте файл класса на GitHub, нажмите на номер или номера соответствующей строки, удерживая Shift, и рядом слева нажмите на троеточие, в выпавшем меню нажмите Copy permalink. В буфер обмена скопируется прямая ссылка на строку этого коммита. Теперь вы её можете просто вставить в текст Issue, как в шаблоне: [Нетологя] (https://https://netology.ru/) без пробела."
    placeholder:  "https://"
  validations:
    required: true

- type: textarea
  attributes:
    label: Шаги воспроизведения
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        1.  
        2.  
        3.  
    render: markdown
  validations:
    required: false
    
- type: input
  id: bug_screen
  attributes:
    label: Скриншот ошибки
    description: "Скриншот - для загрузки изображений вы можете воспользоваться кнопкой, находящейся сразу под полем редактирования текста. Также возможна автозагрузка скриншотов прямо из буфера обмена через Ctrl+V с автовставкой в место нахождения курсора. Шаблон: ![image] (https://https://netology.ru/) без пробела."
    placeholder:  "https://"
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Окружение
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: markdown
  attributes:
    value: |
      ---  Сноски
            [1]:  <br>Во всех .md-файлах, внутри описания баг-репортов используется формат Markdown.
            [2]:  <br>
            [3]:  <br> ↩
            [4]:  <br> ↩
            [5]:  <br>Скопировать из приложения текст лога Ctrl+C и вставить Ctrl+V в этот блок, между ограждающими напоминаниями. Случайное удаление или неправильная вставка текста, приведет к поломке такого отчета. ↩
            
